# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compinfoui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_compDialog(object):
    def setupUi(self, compDialog):
        compDialog.setObjectName("compDialog")
        compDialog.resize(400, 250)
        compDialog.setMinimumSize(QtCore.QSize(400, 250))
        compDialog.setMaximumSize(QtCore.QSize(400, 250))
        self.formLayoutWidget = QtWidgets.QWidget(compDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 60, 361, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setToolTipDuration(-1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cn_li = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cn_li.setText("")
        self.cn_li.setObjectName("cn_li")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cn_li)
        self.ca_li = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ca_li.setObjectName("ca_li")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ca_li)
        self.textBrowser = QtWidgets.QTextBrowser(compDialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 361, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayoutWidget = QtWidgets.QWidget(compDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 170, 361, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.up_bu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.up_bu.setObjectName("up_bu")
        self.gridLayout.addWidget(self.up_bu, 0, 2, 1, 1)
        self.qu_bu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.qu_bu.setObjectName("qu_bu")
        self.gridLayout.addWidget(self.qu_bu, 0, 1, 1, 1)

        self.retranslateUi(compDialog)
        self.qu_bu.clicked.connect(compDialog.close)
        QtCore.QMetaObject.connectSlotsByName(compDialog)

    def retranslateUi(self, compDialog):
        _translate = QtCore.QCoreApplication.translate
        compDialog.setWindowTitle(_translate("compDialog", "Dialog"))
        self.label.setText(_translate("compDialog", "Company Name"))
        self.label_2.setText(_translate("compDialog", "Company Address"))
        self.textBrowser.setHtml(_translate("compDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Company info</span></p></body></html>"))
        self.up_bu.setText(_translate("compDialog", "Upload"))
        self.qu_bu.setText(_translate("compDialog", "Quit"))
