# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectstock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stockdetect(object):
    def setupUi(self, stockdetect):
        stockdetect.setObjectName("stockdetect")
        stockdetect.resize(600, 200)
        stockdetect.setMinimumSize(QtCore.QSize(600, 200))
        stockdetect.setMaximumSize(QtCore.QSize(600, 200))
        self.verticalLayoutWidget = QtWidgets.QWidget(stockdetect)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_2.setOpenLinks(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.textBrowser_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.check = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.check.setObjectName("check")
        self.gridLayout.addWidget(self.check, 0, 0, 1, 1)
        self.exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exit.setObjectName("exit")
        self.gridLayout.addWidget(self.exit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(stockdetect)
        self.exit.clicked.connect(stockdetect.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(stockdetect)

    def retranslateUi(self, stockdetect):
        _translate = QtCore.QCoreApplication.translate
        stockdetect.setWindowTitle(_translate("stockdetect", "Form"))
        self.textBrowser.setHtml(_translate("stockdetect", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; text-decoration: underline;\">Viewmax Internation (HK) CO.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("stockdetect", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; text-decoration: underline;\">Remark: Cannot Revise!</span></p></body></html>"))
        self.check.setText(_translate("stockdetect", "Check"))
        self.exit.setText(_translate("stockdetect", "Exit"))
