# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['main.py',
    'bank.py',
    'callbank.py',
    'callcheqrec.py',
    'callclient.py',
    'callclient_list.py',
    'callcn.py',
    'callcn_list.py',
    'callcompinfo.py',
    'calldetectstock.py',
    'callexp_list.py',
    'callexpense.py',
    'callinv_ed.py',
    'callinv_list.py',
    'callpl_report.py',
    'callproductedit.py',
    'callpur_list.py',
    'callpurchase.py',
    'callreport_stat.py',
    'callret_list.py',
    'callreturn.py',
    'callsell_out_rep.py',
    'cheqrecui.py',
    'client_listui.py',
    'clientui.py',
    'cn_listui.py',
    'cnui.py',
    'compinfoui.py',
    'connectdb.py',
    'detectstock.py',
    'exp_listui.py',
    'expenseui.py',
    'in_edui.py',
    'inv_listui.py',
    'invoice.py',
    'invoiceui.py',
    'mainui.py',
    'pl_reportui.py',
    'producteditui.py',
    'pur_listui.py',
    'purchaseui.py',
    'return_listui.py',
    'returnui.py',
    'sell_out_repui.py',
    'statement_reportui.py'],
    pathex=['D:\\Python\\main'],
    binaries=[('tmp','tmp')],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    icon='D:\\Python\\main\\logo.ico',
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
