# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 100, 581, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.invoice = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.invoice.setObjectName("invoice")
        self.gridLayout.addWidget(self.invoice, 0, 3, 1, 1)
        self.client = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client.setObjectName("client")
        self.gridLayout.addWidget(self.client, 0, 0, 1, 1)
        self.pl = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pl.setObjectName("pl")
        self.gridLayout.addWidget(self.pl, 3, 2, 1, 1)
        self.bank_info = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bank_info.setObjectName("bank_info")
        self.gridLayout.addWidget(self.bank_info, 4, 2, 1, 1)
        self.cheq = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cheq.setObjectName("cheq")
        self.gridLayout.addWidget(self.cheq, 2, 2, 1, 1)
        self.cn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cn.setObjectName("cn")
        self.gridLayout.addWidget(self.cn, 1, 3, 1, 1)
        self.inv_ed = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.inv_ed.setObjectName("inv_ed")
        self.gridLayout.addWidget(self.inv_ed, 2, 3, 1, 1)
        self.expense = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.expense.setObjectName("expense")
        self.gridLayout.addWidget(self.expense, 1, 0, 1, 1)
        self.product = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.product.setObjectName("product")
        self.gridLayout.addWidget(self.product, 0, 2, 1, 1)
        self.comp = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.comp.setObjectName("comp")
        self.gridLayout.addWidget(self.comp, 4, 0, 1, 1)
        self.returnnote = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.returnnote.setObjectName("returnnote")
        self.gridLayout.addWidget(self.returnnote, 2, 0, 1, 1)
        self.purchase = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.purchase.setObjectName("purchase")
        self.gridLayout.addWidget(self.purchase, 1, 2, 1, 1)
        self.sell_out_rep = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sell_out_rep.setObjectName("sell_out_rep")
        self.gridLayout.addWidget(self.sell_out_rep, 3, 3, 1, 1)
        self.statement = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.statement.setObjectName("statement")
        self.gridLayout.addWidget(self.statement, 3, 0, 1, 1)
        self.detect_stock = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.detect_stock.setObjectName("detect_stock")
        self.gridLayout.addWidget(self.detect_stock, 5, 0, 1, 1)
        self.exit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exit.setObjectName("exit")
        self.gridLayout.addWidget(self.exit, 5, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exit.clicked.connect(self.statusbar.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.invoice.setText(_translate("MainWindow", "Invoice"))
        self.client.setText(_translate("MainWindow", "Client"))
        self.pl.setText(_translate("MainWindow", "Profit and Loss"))
        self.bank_info.setText(_translate("MainWindow", "Bank Info"))
        self.cheq.setText(_translate("MainWindow", "Cheq"))
        self.cn.setText(_translate("MainWindow", "CN"))
        self.inv_ed.setText(_translate("MainWindow", "Invoice Edit"))
        self.expense.setText(_translate("MainWindow", "Expense"))
        self.product.setText(_translate("MainWindow", "Product"))
        self.comp.setText(_translate("MainWindow", "Company Info"))
        self.returnnote.setText(_translate("MainWindow", "Return"))
        self.purchase.setText(_translate("MainWindow", "Purchase"))
        self.sell_out_rep.setText(_translate("MainWindow", "Product Sell-out Report"))
        self.statement.setText(_translate("MainWindow", "Statement"))
        self.detect_stock.setText(_translate("MainWindow", "Check Stock Detect"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; text-decoration: underline;\">Viewmax Internation (HK) CO.</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Database: ./viewmax.db              Backup Database: ./backup.db"))
