# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statement_reportui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reportui(object):
    def setupUi(self, reportui):
        reportui.setObjectName("reportui")
        reportui.resize(766, 223)
        self.textBrowser = QtWidgets.QTextBrowser(reportui)
        self.textBrowser.setGeometry(QtCore.QRect(20, 0, 731, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(reportui)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 731, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.start_ed = QtWidgets.QDateEdit(self.layoutWidget)
        self.start_ed.setCalendarPopup(True)
        self.start_ed.setObjectName("start_ed")
        self.horizontalLayout.addWidget(self.start_ed)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.end_ed = QtWidgets.QDateEdit(self.layoutWidget)
        self.end_ed.setCalendarPopup(True)
        self.end_ed.setObjectName("end_ed")
        self.horizontalLayout.addWidget(self.end_ed)
        self.Search_bu = QtWidgets.QPushButton(self.layoutWidget)
        self.Search_bu.setObjectName("Search_bu")
        self.horizontalLayout.addWidget(self.Search_bu)
        self.exit_bu = QtWidgets.QPushButton(reportui)
        self.exit_bu.setGeometry(QtCore.QRect(670, 180, 75, 23))
        self.exit_bu.setObjectName("exit_bu")

        self.retranslateUi(reportui)
        self.exit_bu.clicked.connect(reportui.close)
        QtCore.QMetaObject.connectSlotsByName(reportui)

    def retranslateUi(self, reportui):
        _translate = QtCore.QCoreApplication.translate
        reportui.setWindowTitle(_translate("reportui", "Form"))
        self.textBrowser.setHtml(_translate("reportui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto\',\'RobotoDraft\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:18pt; font-weight:600; color:#000000; background-color:#ffffff;\">Monthly Financial Report</span></p></body></html>"))
        self.label.setText(_translate("reportui", "Start"))
        self.start_ed.setDisplayFormat(_translate("reportui", "yyyy-MM-dd"))
        self.label_2.setText(_translate("reportui", "End"))
        self.end_ed.setDisplayFormat(_translate("reportui", "yyyy-MM-dd"))
        self.Search_bu.setText(_translate("reportui", "Search"))
        self.exit_bu.setText(_translate("reportui", "Exit"))
